# Generated by Django 3.2.4 on 2021-06-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storytask',
            name='end',
        ),
        migrations.RemoveField(
            model_name='storytask',
            name='start',
        ),
        migrations.AddField(
            model_name='storytask',
            name='marked_as',
            field=models.CharField(choices=[('end', 'End')], default='begin', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storytask',
            name='message',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
