# Generated by Django 3.2.11 on 2022-01-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryTask',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.IntegerField()),
                ('channel', models.IntegerField()),
            ],
        ),
    ]
