# Generated by Django 3.2.4 on 2021-06-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_auto_20210621_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytask',
            name='channel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
