# Generated by Django 3.2.5 on 2021-09-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_storytask_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storytask',
            name='marked_as',
        ),
    ]
