# Generated by Django 3.2.5 on 2021-08-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_remove_suggestionchannel_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestionchannel',
            name='keyword',
        ),
    ]
