# Generated by Django 3.2.5 on 2021-08-12 13:41

from django.db import migrations
import ts2.discord.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20210812_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionchannel',
            name='roles_decision',
            field=ts2.discord.models.NumbersListField(default=list),
        ),
        migrations.AddField(
            model_name='suggestionchannel',
            name='roles_voting',
            field=ts2.discord.models.NumbersListField(default=list),
        ),
    ]
