# Generated by Django 3.2.5 on 2021-08-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_remove_suggestionchannel_roles_voting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestionchannel',
            old_name='roles_decision',
            new_name='arbiters',
        ),
    ]
