# Generated by Django 3.2.5 on 2021-08-13 01:41

from django.db import migrations
import ts2.discord.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20210812_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionchannel',
            name='reactions',
            field=ts2.discord.utils.fields.RecordField(default=dict),
        ),
    ]
