# Generated by Django 3.2.5 on 2021-08-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_alter_suggestionchannel_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionchannel',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
