# Generated by Django 3.2.5 on 2021-08-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_suggestionchannel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionchannel',
            name='voting_history',
            field=models.BooleanField(default=True),
        ),
    ]
