[auth]

bot_token = ''
client_id = ''
client_secret = ''
allowed_guilds = []

[default]

prefix = 'd;'
permission = 534689869558

nltk_data = './instance/nltk_data'

[default.mentions]
everyone = false
roles = false
users = false
replied_user = false

[about]

branding = 'dougbot2'
description = ''
twitter = ''

[styles]

[styles.colors]

accent = 0xff980b

[styles.emotes]

failure = ':prohibited:'
pending = ':hourglass_not_done:'
removal = ':wastebasket:'

success = ':check_mark_button:'
warning = ':warning:'

forward = ':fast-forward_button:'
head = ':last_track_button:'
rewind = ':fast_reverse_button:'
tail = ':next_track_button:'

green = ':green_circle:'
red = ':no_entry:'
yellow = ':yellow_square:'
