services:

    redis:
        image: "redis:alpine"
        expose:
            - 6379
        restart: on-failure

    web:
        image: telescope2
        build: .
        environment:
            - DJANGO_SETTINGS_MODULE=ts2.settings.server
        command: "./bin/manage web"
        volumes:
            - instance:/application/instance
            - static:/application/dist
        ports:
            - "8086:8086"
        expose:
            - 8086
        depends_on:
            - redis
        restart: on-failure

    server:
        build: ./nginx
        ports:
            - "8088:80"
        volumes:
            - static:/www
        depends_on:
            - web
        restart: on-failure

    bot:
        image: telescope2
        environment:
            - DJANGO_SETTINGS_MODULE=ts2.settings.deployment
        command: "./bin/manage bot"
        volumes:
            - instance:/application/instance
            - static:/application/dist
        depends_on:
            - web
        restart: on-failure

    backup:
        image: telescope2
        environment:
            - DJANGO_SETTINGS_MODULE=ts2.settings.deployment
        command: "./bin/manage startbackup -o backups"
        volumes:
            - instance:/application/instance
            - backups:/application/backups
        restart: always

volumes:
    instance:
    static:
    backups:
