version: "3.8"

services:
    redis:
        image: 'redis:alpine'
        expose:
            - 6379
        restart: always

    server:
        build: ./nginx
        ports:
            - '8088:80'
        volumes:
            - static:/www
        restart: always
        stop_signal: SIGQUIT

    backup:
        image: telescope2
        environment:
            - DJANGO_SETTINGS_MODULE=dougbot2.conf.deployment
        init: true
        command:
            - ./bin/manage
            - startbackup
            - -o
            - backups
        volumes:
            - instance:/application/instance
            - backups:/application/backups
        restart: always

    web:
        image: telescope2
        build: .
        environment:
            - DJANGO_SETTINGS_MODULE=dougbot2.conf.server
        init: true
        command:
            - ./bin/manage
            - web
        volumes:
            - instance:/application/instance
            - static:/application/dist
        ports:
            - '8086:8086'
        expose:
            - 8086
        depends_on:
            - server
            - redis
            - backup
        restart: unless-stopped

    bot:
        image: telescope2
        environment:
            - DJANGO_SETTINGS_MODULE=dougbot2.conf.deployment
        init: true
        command:
            - ./bin/manage
            - bot
        volumes:
            - instance:/application/instance
            - static:/application/dist
        depends_on:
            - web
            - backup
        restart: unless-stopped

    init:
        image: telescope2
        environment:
            - DJANGO_SETTINGS_MODULE=dougbot2.conf.deployment
        init: true
        command:
            - ./bin/init
        volumes:
            - instance:/application/instance
            - static:/application/dist
        depends_on:
            - web
        restart: 'no'

    migrate:
        image: telescope2
        environment:
            - DJANGO_SETTINGS_MODULE=dougbot2.conf.deployment
        init: true
        command:
            - ./bin/migrate
        volumes:
            - instance:/application/instance
            - static:/application/dist
        depends_on:
            - web
        restart: 'no'

volumes:
    instance:
    static:
    backups:
