services:

    redis:
        image: "redis:alpine"
        expose:
            - 6379

    web:
        image: telescope2
        build: .
        environment:
            - DJANGO_SETTINGS_MODULE=telescope2.settings.deployment
        command: "./bin/manage web"
        volumes:
            - instance:/application/instance
            - static:/application/instance/static
        ports:
            - "8086:8086"
        expose:
            - 8086
        depends_on:
            - redis

    server:
        build: ./nginx
        volumes:
            - static:/application/instance/static
        ports:
            - "8000:80"
        depends_on:
            - web

    bot:
        image: telescope2
        environment:
            - DJANGO_SETTINGS_MODULE=telescope2.settings.deployment
        command: "./bin/manage bot"
        volumes:
            - instance:/application/instance
        depends_on:
            - web

volumes:
    instance:
    static:
