channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.6
  - pip
  - aiodns
  - aiofiles
  - aiohttp
  - asgiref
  - attrs
  - beautifulsoup4
  - cchardet
  - discord.py
  - django
  - djangorestframework
  - inflect
  - lxml
  - markdown
  - nltk
  - pendulum
  - pillow
  - psutil
  - pyjwt
  - python-decouple
  - simplejson
  - sqlite
  - termcolor
  - youtube-dl
  - pip:
    - aiojobs
    - channels
    - daphne
    - django-cacheops
    - django-extensions
    - django-polymorphic
    - django-redis
    - fuzzywuzzy
    - logging-tree
    - more-itertools
    - python-levenshtein
    - redis
    - unidecode
