name: ts2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.6
  - pip
  - aiodns
  - aiofiles
  - aiohttp
  - asgiref
  - attrs
  - beautifulsoup4
  - cchardet
  - discord.py
  - django
  - geopy
  - inflect
  - jinja2
  - lxml
  - markdown
  - nltk
  - pendulum
  - pillow
  - psutil
  - pyjwt
  - pylibmc
  - python-decouple
  - simplejson
  - sqlite
  - termcolor
  - timezonefinder
  - youtube-dl
  - pip:
    - aiojobs
    - channels
    - daphne
    - django-cacheops
    - django-extensions
    - django-polymorphic
    - django-redis
    - django-timezone-field
    - fuzzywuzzy
    - graphene==3.0b7
    - graphene-django==3.0.0b7
    - logging-tree
    - more-itertools
    - python-levenshtein
    - redis
    - unidecode
