# Generated by Django 3.2.5 on 2021-07-12 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0009_alter_user_timezone'),
        ('internet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletimezone',
            name='guild',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='discord.server'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='roletimezone',
            constraint=models.UniqueConstraint(fields=('guild', 'role'), name='uq_role_timezones'),
        ),
    ]
