# Generated by Django 3.2.5 on 2021-07-12 01:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0009_alter_user_timezone'),
        ('internet', '0002_auto_20210711_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roletimezone',
            name='role',
            field=models.ForeignKey(limit_choices_to=models.Q(('guild_id__exact', django.db.models.expressions.F('guild_id'))), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='discord.role'),
        ),
    ]
