# Generated by Django 3.2.5 on 2021-07-12 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0009_alter_user_timezone'),
        ('internet', '0005_alter_roletimezone_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roletimezone',
            name='uq_role_timezones',
        ),
        migrations.RemoveField(
            model_name='roletimezone',
            name='guild',
        ),
        migrations.AlterField(
            model_name='roletimezone',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='discord.role'),
        ),
    ]
