# Generated by Django 3.2.5 on 2021-07-12 02:01

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0006_auto_20210711_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roletimezone',
            name='tz',
        ),
        migrations.AddField(
            model_name='roletimezone',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, choices_display='WITH_GMT_OFFSET', verbose_name='timezone'),
        ),
    ]
