# Generated by Django 3.2.5 on 2021-07-21 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0015_rename_parent_channel_category'),
        ('internet', '0007_auto_20210711_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roletimezone',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timezone', to='discord.role'),
        ),
    ]
