# Generated by Django 3.2.5 on 2021-08-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StringTemplate',
        ),
    ]
