# Generated by Django 3.2.5 on 2021-07-10 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discord', '0005_auto_20210710_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tz', models.CharField(max_length=128)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='discord.role')),
            ],
        ),
    ]
