# Generated by Django 3.2.5 on 2021-08-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickerchannel',
            name='contenttype',
        ),
        migrations.AddField(
            model_name='tickerchannel',
            name='variables',
            field=models.JSONField(blank=True, default='{}'),
            preserve_default=False,
        ),
    ]
