# Generated by Django 3.2.5 on 2021-08-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0004_tickerchannel_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerchannel',
            name='position',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tickerchannel',
            name='variables',
            field=models.JSONField(default=dict),
        ),
    ]
