# Generated by Django 3.2.5 on 2021-08-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0005_auto_20210806_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickerchannel',
            old_name='position',
            new_name='placement',
        ),
    ]
