# Generated by Django 3.2.5 on 2021-07-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftype', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('feature', 'bot feature'), ('qol', 'quality of life'), ('doc', 'documentation'), ('web', 'website')], max_length=32)),
                ('status', models.CharField(choices=[('PL', 'planned'), ('PR', 'prototyping'), ('PS', 'partial'), ('RC', 'finalized'), ('NO', 'never'), ('RM', 'removed'), ('ST', 'abandoned')], max_length=32)),
                ('name', models.TextField()),
            ],
        ),
    ]
