# Generated by Django 3.2.5 on 2021-07-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='ftype',
            field=models.CharField(choices=[('infrastructure', 'infrastructure'), ('feature', 'bot feature'), ('qol', 'quality of life'), ('doc', 'documentation'), ('web', 'website')], max_length=32),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('PL', 'planned'), ('PR', 'draft'), ('PS', 'partial'), ('RC', 'ready'), ('FN', 'finalized'), ('NO', 'never'), ('SP', 'speculative'), ('RM', 'removed'), ('ST', 'abandoned')], max_length=32),
        ),
    ]
