# Generated by Django 3.2.5 on 2021-07-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_feature_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='ftype',
            field=models.CharField(choices=[('infrastructure', 'infrastructure'), ('feature', 'bot feature'), ('qol', 'quality of life'), ('doc', 'documentation'), ('web', 'website'), ('special', 'special')], max_length=32),
        ),
    ]
