# Generated by Django 3.2.5 on 2021-07-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_feature_ftype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='ftype',
            field=models.CharField(choices=[('infrastructure', 'infrastructure'), ('command', 'command'), ('system', 'system'), ('integration', 'integration'), ('qol', 'QoL'), ('doc', 'documentation'), ('web', 'website'), ('special', 'special')], max_length=32),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('01-PL', 'planned'), ('02-PR', 'drafting'), ('03-PS', 'partial'), ('04-RC', 'ready'), ('05-FN', 'frozen'), ('10-SU', 'superseded'), ('20-SP', 'provisional'), ('30-NO', 'never'), ('31-NA', 'unavailable'), ('32-RM', 'removed'), ('33-ST', 'abandoned')], max_length=32),
        ),
    ]
