# Generated by Django 3.2.5 on 2021-07-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_bugreport_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
