# Generated by Django 3.2.4 on 2021-06-11 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('snowflake', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
                ('prefix', models.CharField(default='t;', max_length=16)),
            ],
            options={
                'verbose_name': 'guild preference',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('snowflake', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=120, verbose_name='username')),
                ('discriminator', models.IntegerField()),
                ('timezone', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('snowflake', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=120)),
                ('color', models.IntegerField()),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='discord.server')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('snowflake', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
                ('nickname', models.CharField(blank=True, max_length=64)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='discord.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='discord.user')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('snowflake', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=120)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='discord.server')),
            ],
        ),
    ]
