# Generated by Django 3.2.4 on 2021-06-13 20:59

from django.db import migrations, models
import django.db.models.deletion
import telescope2.discord.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelCategory',
            fields=[
                ('snowflake', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=120)),
                ('type', models.IntegerField(choices=[(0, 'Text'), (1, 'Private'), (2, 'Voice'), (3, 'Group'), (4, 'Category'), (5, 'News'), (6, 'Store'), (13, 'Stage Voice')], default=4, editable=False)),
            ],
            options={
                'verbose_name': 'channelcategory',
                'verbose_name_plural': 'channelcategories',
            },
            bases=(telescope2.discord.models.NamingMixin, telescope2.discord.models.SubclassMetaMixin, models.Model, telescope2.discord.models.ModelTranslator),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('snowflake', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
                ('prefix', models.CharField(default='t;', max_length=16)),
                ('_extensions', models.TextField(blank=True)),
                ('everyone_perms', telescope2.discord.models.PermissionField(verbose_name='default permissions')),
            ],
            options={
                'verbose_name': 'server',
                'verbose_name_plural': 'servers',
            },
            bases=(telescope2.discord.models.NamingMixin, telescope2.discord.models.SubclassMetaMixin, models.Model, telescope2.discord.models.ModelTranslator),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('snowflake', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=120, verbose_name='username')),
                ('discriminator', models.IntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=(telescope2.discord.models.NamingMixin, telescope2.discord.models.SubclassMetaMixin, models.Model, telescope2.discord.models.ModelTranslator),
        ),
        migrations.CreateModel(
            name='ServerChannel',
            fields=[
                ('snowflake', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=120)),
                ('type', models.IntegerField(choices=[(0, 'Text'), (1, 'Private'), (2, 'Voice'), (3, 'Group'), (4, 'Category'), (5, 'News'), (6, 'Store'), (13, 'Stage Voice')])),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subchannels', to='discord.channelcategory')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='discord.server')),
            ],
            options={
                'verbose_name': 'serverchannel',
                'verbose_name_plural': 'serverchannels',
            },
            bases=(telescope2.discord.models.NamingMixin, telescope2.discord.models.SubclassMetaMixin, models.Model, telescope2.discord.models.ModelTranslator),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('snowflake', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=120)),
                ('color', telescope2.discord.models.ColorField()),
                ('perms', telescope2.discord.models.PermissionField(verbose_name='permissions')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='discord.server')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
            bases=(telescope2.discord.models.NamingMixin, telescope2.discord.models.SubclassMetaMixin, models.Model, telescope2.discord.models.ModelTranslator),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('snowflake', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
                ('nickname', models.CharField(blank=True, max_length=64)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='discord.server')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='discord.user')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
            bases=(telescope2.discord.models.NamingMixin, telescope2.discord.models.SubclassMetaMixin, models.Model, telescope2.discord.models.ModelTranslator),
        ),
        migrations.AddField(
            model_name='channelcategory',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='discord.server'),
        ),
    ]
