# Generated by Django 3.2.4 on 2021-06-13 21:07

from django.db import migrations
import telescope2.discord.models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='everyone_perms',
        ),
        migrations.AddField(
            model_name='server',
            name='perms',
            field=telescope2.discord.models.PermissionField(default=0, verbose_name='default permissions'),
        ),
    ]
