# Generated by Django 3.2.4 on 2021-06-13 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_auto_20210613_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelcategory',
            options={'verbose_name': 'channel category'},
        ),
        migrations.AlterModelOptions(
            name='serverchannel',
            options={'verbose_name': 'channel'},
        ),
        migrations.AlterField(
            model_name='channelcategory',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='discord.server'),
        ),
        migrations.AlterField(
            model_name='serverchannel',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='discord.server'),
        ),
    ]
