# Generated by Django 3.2.4 on 2021-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_auto_20210605_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guildpreference',
            options={'verbose_name': 'guild preference'},
        ),
        migrations.AddField(
            model_name='guildpreference',
            name='guild_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
