# Generated by Django 3.2.4 on 2021-06-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_auto_20210612_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='_extensions',
            field=models.TextField(blank=True),
        ),
    ]
