# Generated by Django 3.2.4 on 2021-06-06 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0003_auto_20210605_0638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guildpreference',
            options={'permissions': [('manage_servers', 'Can invite the bot to servers')], 'verbose_name': 'guild preference'},
        ),
    ]
