# Generated by Django 3.2.4 on 2021-06-13 23:45

from django.db import migrations, models
import django.db.models.deletion
import telescope2.discord.models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0003_auto_20210613_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('snowflake', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=120)),
                ('type', models.IntegerField(choices=[(0, 'Text'), (1, 'Private'), (2, 'Voice'), (3, 'Group'), (4, 'Category'), (5, 'News'), (6, 'Store'), (13, 'Stage Voice')])),
                ('order', models.IntegerField(default=0)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='discord.server')),
            ],
            options={
                'verbose_name': 'channel',
                'verbose_name_plural': 'channels',
            },
            bases=(telescope2.discord.models.NamingMixin, telescope2.discord.models.SubclassMetaMixin, models.Model, telescope2.discord.models.ModelTranslator),
        ),
        migrations.RemoveField(
            model_name='serverchannel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='serverchannel',
            name='guild',
        ),
        migrations.AddField(
            model_name='role',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ChannelCategory',
        ),
        migrations.DeleteModel(
            name='ServerChannel',
        ),
    ]
