# Generated by Django 3.2.4 on 2021-06-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0004_alter_guildpreference_options'),
    ]

    operations = [
        migrations.RenameModel('GuildPreference', 'Server'),
    ]
