# Generated by Django 3.2.4 on 2021-06-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0004_auto_20210613_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
