# Generated by Django 3.2.4 on 2021-06-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0005_server_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('channels', models.ManyToManyField(related_name='_discord_commandconstraint_channels_+', to='discord.Channel')),
                ('commands', models.ManyToManyField(related_name='constraints', to='discord.BotCommand')),
                ('roles', models.ManyToManyField(related_name='_discord_commandconstraint_roles_+', to='discord.Role')),
            ],
        ),
    ]
