# Generated by Django 3.2.4 on 2021-06-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0005_auto_20210607_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='guild_id',
            new_name='gid',
        ),
    ]
