# Generated by Django 3.2.4 on 2021-06-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0006_commandconstraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botcommand',
            options={'verbose_name': 'bot command'},
        ),
        migrations.AlterModelOptions(
            name='commandconstraint',
            options={'verbose_name': 'command constraint'},
        ),
    ]
