# Generated by Django 3.2.4 on 2021-06-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0006_rename_guild_id_discordserver_gid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': 'guild preference'},
        ),
    ]
