# Generated by Django 3.2.4 on 2021-06-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0007_alter_server_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='gid',
            field=models.IntegerField(unique=True, verbose_name='guild id'),
        ),
    ]
