# Generated by Django 3.2.4 on 2021-06-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0007_auto_20210613_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandconstraint',
            name='guild',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='command_constraints', to='discord.server'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commandconstraint',
            name='type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Any'), (2, 'All')], default=0),
            preserve_default=False,
        ),
    ]
