# Generated by Django 3.2.4 on 2021-06-15 15:20

from django.db import migrations, models
import django.db.models.deletion
import telescope2.discord.models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0008_auto_20210614_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandConstraintList',
            fields=[
                ('guild', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='command_constraints', serialize=False, to='discord.server')),
            ],
            options={
                'verbose_name': 'command constraint list',
            },
            bases=(telescope2.discord.models.NamingMixin, telescope2.discord.models.SubclassMetaMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='commandconstraint',
            name='guild',
        ),
        migrations.AddField(
            model_name='commandconstraint',
            name='collection',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='discord.commandconstraintlist'),
            preserve_default=False,
        ),
    ]
