# Generated by Django 3.2.4 on 2021-06-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0009_auto_20210615_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandconstraint',
            name='name',
            field=models.TextField(),
        ),
    ]
