# Generated by Django 3.2.4 on 2021-06-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0012_server_error_handling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='error_handling',
        ),
        migrations.AddField(
            model_name='server',
            name='logging',
            field=models.JSONField(default=dict, verbose_name='logging config'),
        ),
    ]
