# Generated by Django 3.2.4 on 2021-06-19 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discord', '0014_auto_20210618_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_servers', to=settings.AUTH_USER_MODEL),
        ),
    ]
