# Generated by Django 3.2.4 on 2021-06-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0015_alter_server_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandconstraint',
            name='error_msg',
            field=models.TextField(blank=True, verbose_name='error message'),
        ),
    ]
