# Generated by Django 3.2.5 on 2021-08-06 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discord', '0020_auto_20210730_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerChannel',
            fields=[
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='discord.channel')),
                ('contenttype', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('refresh', models.FloatField()),
                ('expire', models.DateTimeField(null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='discord.channel')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='discord.server')),
            ],
        ),
    ]
