# Generated by Django 3.2.5 on 2021-08-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0003_alter_tickerchannel_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerchannel',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
