# Generated by Django 3.2.5 on 2021-08-10 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0006_rename_position_tickerchannel_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickerchannel',
            name='server',
        ),
    ]
