# Generated by Django 3.2.5 on 2021-08-21 12:29

from django.db import migrations, models
import ts2.discord.utils.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0007_remove_tickerchannel_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerchannel',
            name='created',
            field=models.DateTimeField(default=ts2.discord.utils.datetime.utcnow),
        ),
    ]
