# Generated by Django 3.2.5 on 2021-07-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_feature_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('PL', 'planned'), ('PR', 'drafting'), ('PS', 'partial'), ('RC', 'ready'), ('FN', 'frozen'), ('NO', 'never'), ('SP', 'speculative'), ('NA', 'no support'), ('RM', 'removed'), ('ST', 'abandoned'), ('SU', 'superseded')], max_length=32),
        ),
    ]
