# Generated by Django 3.2.5 on 2021-07-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_bugreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='topic',
            field=models.IntegerField(choices=[(1, 'Commands'), (2, 'Documentation'), (3, 'Website'), (4, 'Feedback')], verbose_name='report type'),
        ),
    ]
