# Generated by Django 3.2.5 on 2021-07-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_bugreport_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='topic',
            field=models.IntegerField(choices=[(1, 'Commands errors'), (2, 'Documentation errors'), (3, 'Website issues'), (4, 'Suggestion & feedback')], verbose_name='report type'),
        ),
    ]
