# Generated by Django 3.2.5 on 2021-07-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_bugreport_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='slug',
        ),
        migrations.AddField(
            model_name='feature',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
