# Generated by Django 3.2.5 on 2021-08-06 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0020_auto_20210730_1553'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickerchannel',
            name='id',
        ),
        migrations.AddField(
            model_name='tickerchannel',
            name='content',
            field=models.TextField(default='Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickerchannel',
            name='contenttype',
            field=models.CharField(default='text/plain', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tickerchannel',
            name='channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='discord.channel'),
        ),
    ]
