# Generated by Django 3.2.5 on 2021-08-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_auto_20210806_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerchannel',
            name='expire',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tickerchannel',
            name='refresh',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
