# Generated by Django 3.2.7 on 2021-10-21 23:20

from django.db import migrations, models
import django.db.models.deletion
import ts2.web.contrib.cupboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discord', '0021_auto_20210812_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=ts2.web.contrib.cupboard.models.ServerResource.upload_path)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discord.server')),
            ],
        ),
    ]
