# Generated by Django 3.2.4 on 2021-06-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_servers', 'Can invite the bot to servers')]},
        ),
    ]
