# Generated by Django 3.2.5 on 2021-07-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0006_auto_20210715_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='channel',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
