# Generated by Django 3.2.5 on 2021-07-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0007_alter_accesscontrol_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscontrol',
            name='specificity',
        ),
    ]
