# Generated by Django 3.2.11 on 2022-02-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dougbot2', '0002_remove_server_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisabledApp',
        ),
    ]
