# Generated by Django 3.2.5 on 2021-07-11 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0006_auto_20210710_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(blank=True)),
                ('name', models.CharField(max_length=120)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='discord.server')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stringtemplate',
            constraint=models.UniqueConstraint(fields=('server_id', 'name'), name='uq_discord_stringtemplate_server_id_name'),
        ),
    ]
