# Generated by Django 3.2.5 on 2021-07-11 23:57

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0008_auto_20210711_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, choices_display='WITH_GMT_OFFSET', verbose_name='timezone'),
        ),
    ]
