# Generated by Django 3.2.5 on 2021-07-21 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0013_auto_20210714_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discord.channel'),
        ),
    ]
