# Generated by Django 3.2.5 on 2021-07-21 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0014_channel_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='parent',
            new_name='category',
        ),
    ]
