# Generated by Django 3.2.5 on 2021-07-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0018_auto_20210724_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StringTemplate',
        ),
    ]
