# Generated by Django 3.2.5 on 2021-07-30 22:53

from django.db import migrations, models


def field_forward(apps, schema_editor):
    Server = apps.get_model('discord', 'Server')
    Server.objects.all().update(readable=[], writable=[])


def field_backward(apps, schema_editor):
    Server = apps.get_model('discord', 'Server')
    Server.objects.all().update(readable=32, writable=32)


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0019_delete_stringtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='readable',
            field=models.JSONField(default=list, verbose_name='readable roles'),
        ),
        migrations.AlterField(
            model_name='server',
            name='writable',
            field=models.JSONField(default=list, verbose_name='writable roles'),
        ),
        migrations.RunPython(field_forward, field_backward, atomic=True),
    ]
