# Generated by Django 3.2.11 on 2022-01-31 15:37

from django.db import migrations, models

import dougbot2.models
import dougbot2.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SuggestionChannel",
            fields=[
                (
                    "snowflake",
                    models.BigIntegerField(
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("title", models.TextField(default="Suggestion")),
                ("description", models.TextField(blank=True)),
                ("upvote", models.CharField(blank=True, default="🔼", max_length=512)),
                ("downvote", models.CharField(blank=True, default="🔽", max_length=512)),
                ("requires_text", models.BooleanField(default=True)),
                ("requires_uploads", models.IntegerField(default=0)),
                ("requires_links", models.IntegerField(default=0)),
                ("reactions", dougbot2.utils.fields.RecordField(default=dict)),
                ("arbiters", dougbot2.utils.fields.NumbersListField(default=list)),
                ("voting_history", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(dougbot2.models.NamingMixin, models.Model),
        ),
    ]
