# Generated by Django 3.2.5 on 2021-08-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_remove_suggestionchannel_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionchannel',
            name='approve',
            field=models.CharField(blank=True, default='✅', max_length=512),
        ),
        migrations.AlterField(
            model_name='suggestionchannel',
            name='downvote',
            field=models.CharField(blank=True, default='🔽', max_length=512),
        ),
        migrations.AlterField(
            model_name='suggestionchannel',
            name='reject',
            field=models.CharField(blank=True, default='🚫', max_length=512),
        ),
        migrations.AlterField(
            model_name='suggestionchannel',
            name='upvote',
            field=models.CharField(blank=True, default='🔼', max_length=512),
        ),
    ]
