# Generated by Django 3.2.5 on 2021-08-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20210812_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestionchannel',
            name='roles_voting',
        ),
    ]
