# Generated by Django 3.2.5 on 2021-08-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_rename_roles_decision_suggestionchannel_arbiters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestionchannel',
            name='approve',
        ),
        migrations.RemoveField(
            model_name='suggestionchannel',
            name='reject',
        ),
        migrations.AddField(
            model_name='suggestionchannel',
            name='reactions',
            field=models.JSONField(default=dict),
        ),
    ]
