# Generated by Django 3.2.5 on 2021-07-10 01:45

from django.db import migrations, models
import ts2.discord.models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_auto_20210622_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklisted',
            fields=[
                ('snowflake', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'verbose_name': 'blacklisted entity',
            },
            bases=(ts2.discord.models.NamingMixin, models.Model),
        ),
    ]
