# Generated by Django 3.2.5 on 2021-07-10 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0003_blacklisted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklisted',
            options={'verbose_name': 'blacklisted entity', 'verbose_name_plural': 'blacklisted entities'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
