# Generated by Django 3.2.5 on 2021-07-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0007_auto_20210710_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='datefmt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timefmt',
        ),
        migrations.AddField(
            model_name='user',
            name='datetimefmt',
            field=models.TextField(blank=True, verbose_name='datetime format'),
        ),
    ]
