# Generated by Django 3.2.5 on 2021-07-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0009_alter_user_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandconstraint',
            name='collection',
        ),
        migrations.AddField(
            model_name='commandconstraint',
            name='guild',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='command_constraints', to='discord.server'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CommandConstraintList',
        ),
    ]
