# Generated by Django 3.2.5 on 2021-07-13 00:52

from django.db import migrations, models
import ts2.discord.models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0010_auto_20210712_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='prefix',
            field=models.CharField(default='t;', max_length=16, validators=[ts2.discord.models.validate_prefix]),
        ),
    ]
