# Generated by Django 3.2.5 on 2021-07-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0011_alter_server_prefix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
