# Generated by Django 3.2.5 on 2021-07-15 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0012_auto_20210714_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandconstraint',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='commandconstraint',
            name='commands',
        ),
        migrations.RemoveField(
            model_name='commandconstraint',
            name='guild',
        ),
        migrations.RemoveField(
            model_name='commandconstraint',
            name='roles',
        ),
        migrations.DeleteModel(
            name='BotCommand',
        ),
        migrations.DeleteModel(
            name='CommandConstraint',
        ),
    ]
