# Generated by Django 3.2.5 on 2021-08-12 13:41

from django.db import migrations
import ts2.discord.models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0020_auto_20210730_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='readable',
            field=ts2.discord.models.NumbersListField(default=list, verbose_name='readable roles'),
        ),
        migrations.AlterField(
            model_name='server',
            name='writable',
            field=ts2.discord.models.NumbersListField(default=list, verbose_name='writable roles'),
        ),
    ]
