# Generated by Django 3.2.11 on 2022-01-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklisted',
            fields=[
                ('snowflake', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'verbose_name': 'blacklisted entity',
                'verbose_name_plural': 'blacklisted entities',
            },
        ),
    ]
