# Generated by Django 3.2.11 on 2022-02-05 06:14

from django.db import migrations, models

import dougbot2.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("firewall", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.TextField()),
                ("channel_id", models.BigIntegerField()),
                ("roles", dougbot2.utils.fields.NumbersListField()),
                ("enabled", models.BooleanField()),
            ],
        ),
        migrations.AddIndex(
            model_name="accessrule",
            index=models.Index(
                fields=["command", "channel_id"], name="firewall_ac_command_c0ceab_idx"
            ),
        ),
    ]
