# Generated by Django 3.2.11 on 2022-02-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firewall", "0002_auto_20220204_2214"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrule",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
