# Generated by Django 3.2.7 on 2021-11-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rolemenu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.BigIntegerField()),
                ("message_id", models.BigIntegerField()),
                ("title", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name="rolecounter",
            index=models.Index(
                fields=["channel_id", "message_id"],
                name="rolemenu_ro_channel_527488_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolestatistics",
            constraint=models.UniqueConstraint(
                fields=("channel_id", "message_id"), name="msg_id"
            ),
        ),
    ]
