# Generated by Django 3.2.7 on 2021-11-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rolemenu", "0003_auto_20211130_0704"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolecounter",
            name="guild_id",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rolecounter",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="rolemenu.rolestatistics",
            ),
        ),
        migrations.AddIndex(
            model_name="rolecounter",
            index=models.Index(
                fields=["guild_id"], name="rolemenu_ro_guild_i_e786ab_idx"
            ),
        ),
    ]
