# Generated by Django 3.2.5 on 2021-07-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTimezone',
        ),
    ]
