# Generated by Django 3.2.5 on 2021-07-10 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_delete_usertimezone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleTimezone',
        ),
    ]
