# Generated by Django 3.2.5 on 2021-08-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_auto_20210806_0740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TickerChannel',
        ),
    ]
