# Generated by Django 3.2.5 on 2021-07-15 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discord', '0012_auto_20210714_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commands', models.JSONField(default=list)),
                ('channels', models.JSONField(default=list)),
                ('roles', models.JSONField(default=list)),
                ('modifier', models.IntegerField(choices=[(0, 'none of'), (1, 'any of'), (2, 'all of')])),
                ('action', models.CharField(choices=[('enabled', 'Commands are enabled'), ('disabled', 'Commands are disabled')], max_length=120)),
                ('specificity', models.IntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl', to='discord.server')),
            ],
        ),
    ]
