# Generated by Django 3.2.5 on 2021-07-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0002_auto_20210714_1750'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accesscontrol',
            name='idx_acl_server_id_command',
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='channels',
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='channel',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='accesscontrol',
            index=models.Index(fields=['server_id', 'command', 'channel'], name='idx_acl_server_command_channel'),
        ),
    ]
