# Generated by Django 3.2.5 on 2021-07-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0003_auto_20210714_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='channel',
            field=models.BigIntegerField(null=True),
        ),
    ]
