# Generated by Django 3.2.5 on 2021-07-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0004_alter_accesscontrol_channel'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accesscontrol',
            name='idx_acl_server_command_channel',
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='accesscontrol',
            index=models.Index(fields=['server_id', 'command', 'channel'], name='ix_acl_server_command_channel'),
        ),
        migrations.AddConstraint(
            model_name='accesscontrol',
            constraint=models.UniqueConstraint(fields=('server_id', 'name'), name='uq_acl_accesscontrol_server_id_name'),
        ),
    ]
