# Generated by Django 3.2.5 on 2021-07-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0005_auto_20210714_1928'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accesscontrol',
            name='uq_acl_accesscontrol_server_id_name',
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='command',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
