# Generated by Django 3.2.11 on 2022-02-03 13:42

import timezone_field.fields
from django.db import migrations, models

import dougbot2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DateTimeSettings",
            fields=[
                (
                    "snowflake",
                    models.BigIntegerField(
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(
                        blank=True,
                        choices_display="WITH_GMT_OFFSET",
                        verbose_name="timezone",
                    ),
                ),
                (
                    "formatting",
                    models.TextField(
                        blank=True,
                        default="D MMM YYYY h:mm:ss A",
                        verbose_name="datetime format",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dougbot2.models.NamingMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RoleTimezone",
            fields=[
                (
                    "snowflake",
                    models.BigIntegerField(
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(
                        blank=True,
                        choices_display="WITH_GMT_OFFSET",
                        verbose_name="timezone",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dougbot2.models.NamingMixin, models.Model),
        ),
    ]
