# Generated by Django 3.2.4 on 2021-06-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryTask',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.IntegerField(blank=True)),
                ('end', models.IntegerField(blank=True)),
            ],
        ),
    ]
